title: Jordan Terry
description: Rambles from Jordan.

url: https://jordanterry.co.uk
baseurl:

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /
    - title: About
      url: /about/
    - title: Talks
      url: /categories/talks/
    - title: Software
      url: /categories/software/
    - title: Flying
      url: /categories/flying/
    - title: French
      url: /categories/french/

social:
    github: jordanterry
    linkedin: jordan-terry

google_analytics: "G-B5WY7FZCS8"

theme_config:
    appearance: "auto"
    back_home_text: ".."
    date_format: "%Y-%m-%d"
    show_description: false
    lowercase_titles: true
