title: Jordan Terry
description: Software engineer, pilot, long-distance cyclist.

url: https://jordanterry.co.uk
baseurl:

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

social:
    github: jordanterry
    linkedin: jordan-terry

google_analytics: "G-B5WY7FZCS8"

theme_config:
    appearance: "auto"
    back_home_text: ".."
    date_format: "%Y-%m-%d"
    show_description: false
    lowercase_titles: true
